server:
  port: 2021
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://118.31.65.0:3306/sob_blog_system?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  redis:
    host: 39.106.150.176
#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1 #正常
  type-aliases-package: com.wwjjbt.sob_blog_system_mp.pojo
#      /usr/local/java/Envaroment/sobBlog/upload
sob.blog.image.save-Path: /usr/app/upload
sob.blog.image.max-size: 2097152  #2mb
#  控制es的连接地址
es.connection.host: 101.200.196.94
