server:
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sob_blog_system?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  redis:
    host: 39.106.150.176
#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1 #正常
  mapper-locations: classpath:com/wwjjbt/sob_blog_system_mp/mapper/xml/*Mapper.xml
  type-aliases-package: com.wwjjbt.sob_blog_system_mp.pojo

sob.blog.image.save-Path: C:\IDEA\sob_blog_system_mp\src\main\resources\static\images\
sob.blog.image.max-size: 2097152  #2mb
es.connection.host: 127.0.0.1